#!/usr/bin/env bash
# installs nginx and configures the server to the desired options

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://www.google.com;
    }
}" > /etc/nginx/sites-available/default
service nginx start
