#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes

echo "Hour: 0"
m=1
while [ $m -lt 60 ]; do
	echo $m
	m=$((m+1))
done
echo "Hour: 1"
h=1
while [ $h -le 12 ]; do
	echo $h
	h=$((h+1))
done
